CocoaPods/guides.cocoapods.org

- source/making/making-a-cocoapod.html.md
- source/using/the-podfile.html.md
... by replacing old dead links with new functioning links with similar content.
See https://github.com/CocoaPods/CocoaPods/issues/3000 for details.
> Updated RubyGems Versioning Policies and RubyGems version specifiers links

- source/making/private-cocoapods.html.md
I've mad a couple of changes which I hope will improve the instructions of creating and using a Private Repo to newcomers.
> Trying to make the instructions clearer in the Private Repo pages

- source/using/a-gemfile.html.md
https://github.com/CocoaPods/CocoaPods/issues/4506#issuecomment-154180112
> Using CocoaPods master also requires using core master.

- .travis.yml
> [Travis] Use a git credential helper

- source/making/using-pod-lib-create.html.md
Figured this is a good place for people new enough to not know about this.
> Add a note about requiring a class be public in swift projects

- source/layouts/quality_indexes.slim
Updates the submodule to the latest version of CocoaDocs-API
> Update the QI documentation

- .gitmodules
- Rakefile
- config.rb
- lib/doc.rb
- lib/doc/generators/commands.rb
- lib/doc/generators/dsl.rb
This way, we're not manually mangling load paths and updating submodules.  (It will now also use CLAide to ensure all the default plugins are required)
\c @mtitolo @orta
> Use gems from the Gemfile rather than submodules

- source/using/pod-install-vs-update.html.md
- source/using/using-cocoapods.html.md
> Adding a guide to explain pod install vs. pod update

- source/using/pod-install-vs-update.html.md
This is the follow-up of #101 to address late feedback after initial merge. \cc @orta @kylef
> pod install vs update - review

- source/using/using-cocoapods.html.md
Fixes https://github.com/CocoaPods/cocoapods.org/issues/247
> Fix broken guides link

- lib/doc/generators/dsl.rb
- source/templates/dsl.html.slim
Depends upon https://github.com/CocoaPods/Core/pull/302, but we can't merge this until 1.0.0.beta.3 is released.
Closes https://github.com/CocoaPods/CocoaPods/issues/4842.
\c @orta
> Show installation options in Podfile DSL docs

- source/using/the-podfile.html.md
- source/using/using-cocoapods.html.md
> Updated Podfiles in the guides to the new syntax

- source/templates/dsl.html.slim
> [DSL] Dont print supported keys section when it is empty

- Rakefile
I missed a few in https://github.com/CocoaPods/guides.cocoapods.org/pull/111
> [Commands] Add the rest of the default commands

- lib/navigation_helpers.rb
While I'm not crazy on white on grey, this is definitely an improvement 👍 
From:
To
> Move Required into the navigation on Podspec- fixes #113

- Rakefile
- lib/doc/code_objects.rb
Works like a charm. See: https://github.com/CocoaPods/cocoapods-deintegrate/pull/23.
> [YARD] Use custom tag for CocoaPods Availability

- source/using/faq.html.md
> [FAQ] We're 1.0 now

- source/making/specs-and-specs-repo.html.md
- source/using/faq.html.md
- source/using/getting-started.html.md
- source/using/troubleshooting.html.md
> OS X => macOS

- lib/doc/code_objects.rb
- lib/doc/generators/dsl.rb
- source/templates/dsl.html.slim
[Sister PR in shared_resources](https://github.com/CocoaPods/shared_resources/pull/21)
cc @orta
> [DSL] Include params for methods

- config.rb
- source/templates/dsl.html.slim
Lowers the barrier to getting better docs from contributors, for example https://github.com/CocoaPods/CocoaPods/issues/5673#issuecomment-235387146
> Add a PR button to the reference sections

- source/using/troubleshooting.html.md
> Remove errant punctuation bullet.

- source/making/using-pod-lib-create.html.md
> Fixed grammar issue with it's vs its

- source/using/troubleshooting.html.md
See
- https://stackoverflow.com/a/33675206/377369
- https://stackoverflow.com/a/31725558/377369
This would have saved me a few hours.
> Added a note about using the Workspace

- CONTRIBUTING.md
Fix the Markdown headers to properly generate formatted content (including the GitHub web rendering).
> Fix Markdown headers

- source/using/faq.html.md
Related to https://github.com/CocoaPods/CocoaPods/pull/7917
Probably the wrong place to put this, but nowhere else stood out as a better place
> Add a note about using CP_HOME_DIR

- source/using/unreleased-features.html.md
> Mention installing Bundler in using unreleased features page

- source/using/getting-started.html.md
.profile is technically .bash_profile , so I changed it to that also
> Add how to access the .profile file

- source/making/development-cocoapods.html.md
- source/making/private-cocoapods.html.md
- source/making/specs-and-specs-repo.html.md
Hi, I noticed that the Guides mention Development Pods, but never actually describe how to set them up, so I added an extra page for those based on information out there on the web.
🌈
> Add missing Development Pods Guide

- source/contributing/dev-environment.html.md
Awesome Print moved to another repo.
> Update "Awesome Print" url

- source/using/the-podfile.html.md
https://github.com/CocoaPods/Core/pull/716#issuecomment-1097268997
> Use CDN source in example

- source/using/the-podfile.html.md
> Update link to Eigen Podfile sample
