CocoaPods/guides.cocoapods.org

- source/using/the-podfile.html.md
This might be obvious to those who use the system already but the docs failed to mention what the actual filename of a Podfile should be.
> Made sure the name of the Podfile is explicitly stated.

- source/using/using-cocoapods.html.md
As per @orta's suggestion, here are some suggested improvements to make these 2 sections much clearer. I and the other folks on my team had trouble understanding this as it was originally written without reading it a few times, hopefully this is clearer!
> Improve discussion of checking in Pods directory

- source/making/getting-setup-with-trunk.html.md
Well, this started small and got out of hand! My goals were:
- Trunk is a Proper Important Thing and we should capitalize Trunk in sentences
- Emphasize the parallels between pushing to Trunk and to private specs repos, and add a link to the docs page on the latter
- Show sample usage with full command examples favored over command names
- Try to clarify Trunk sessions on multiple computers
Comments welcome!
> [Trunk] my kingdom for Trunk

- source/making/private-cocoapods.html.md
Noticed that achieved was misspelled on the 'Private Pods' page on guides.  Fixed
> acheived [sic] misspelled.  Should be 'achieved'

- source/using/the-podfile.html.md
I'm not an expert but I think that updated syntax is correct.
Similar change is also need at these URLs: 
http://guides.cocoapods.org/syntax/podfile.html#podfile
https://guides.cocoapods.org/syntax/podfile.html
I might have chance to track them down if I get a seat and some 3G signal on the train tomorrow.
> Updated for version 0.38 changes.

- source/using/the-podfile.html.md
I’m not a native English speaker, but I believe these should all be “its”.
> [Typo] Fix “it’s”/“its”

- Rakefile
- lib/doc/code_objects.rb
- lib/doc/generators/commands.rb
- source/templates/commands.html.slim
Closes #110.
This pushes YARD tags for Commands into the docs. For example, 
Adding the `# @since` annotation to Deintegrate,
> Availability support for CocoaPods commands

- source/making/getting-setup-with-trunk.html.md
Makes it explicit that you need to have registered an account before you can add someone
> Improve the trunk guide

- Rakefile
Forgot that the subcommands are nested another level deep. Now this loads trunk, ipc, etc.
> [Rakefile] Load subcommands into YARD

- source/contributing/dev-environment.html.md
- source/contributing/tickets-handling.html.md
- source/making/getting-setup-with-trunk.html.md
- source/making/private-cocoapods.html.md
- source/making/quality-indexes.html.md
- source/making/specs-and-specs-repo.html.md
Looks like there was a bunch of duplicates in the ordering, so any change to the site would shuffle a few of the footer links - https://github.com/CocoaPods/guides.cocoapods.org/commit/4ee8dfe9d423f1ddc618994abcc8a349879a259b
> Use a more determinate ordering system for the guides

- source/making/making-a-cocoapod.html.md
I noticed that the commands related to pushing podspecs were kind of hard to notice because of being inlined. This change should help people skimming this guide.
> Make visual scanning of commands easier

- source/making/specs-and-specs-repo.html.md
See https://github.com/CocoaPods/CocoaPods/issues/8098#issuecomment-440282398.
Trunk push already performs a lint under the hood.
> Don't tell users to run `spec lint` before `trunk push`

- Rakefile
- source/index.html.slim
- source/layouts/layout.slim
- source/making/index.html.md
- source/making/quality-indexes.html.md
- source/plugins/environment-vars.html.md
- source/plugins/index.html.md
- source/plugins/optimising-ci-times.html.md
- source/plugins/pre-compiling-dependencies.html.md
- source/plugins/setting-up-plugins.html.slim
- source/plugins/using-pods-for-closed-source-libs.html.md
- source/using/a-gemfile.html.md
I was thinking about how I didn't know that CocoaPods Binary didn't exist in  https://github.com/signalapp/Signal-iOS/pull/4096 and came to the conclusion that there must be a lot of plugins people don't know about.
This adds a 5th section of docs to the guides: Being a consumer, being a producer, API reference, contributing back to CP and now plugins.
I did some re-balancing of the UI a bit to make the section fit, and it feels reasonable to me 👍
> Highlight useful & popular plugins from the community

- .travis.yml
The bundler 2.0 update meant that the deploys won't work on our old ruby version, this updates that.
> Update the ruby version

- source/making/specs-and-specs-repo.html.md
Closes #147
We could potentially add more context here, but for now removing the dead link seems worthwhile.
> Remove dead link in `specs-and-specs-repo` page

- Gemfile
- Gemfile.lock
This will fix guides for 1.8.0.beta.1. It can be removed in beta2 where the Core gem properly specifies this dependency as added here https://github.com/CocoaPods/Core/pull/577
> Add concurrent-ruby gem

- config.rb
- source/layouts/layout.slim
Solves the strange titles of the DSL Guides.
> Remove the <span>v1.8.0</span> from HTML head title

- source/making/private-cocoapods.html.md
Changes the URL to the [Artsy CocoaPods specs repository](https://github.com/artsy/Specs) from `git@github:artsy/Specs.git` to `https://github.com/artsy/Specs.git`.
```console
$ pod repo add artsy-specs git@github:artsy/Specs.git
Cloning spec repo `artsy-specs` from `git@github:artsy/Specs.git`
[!] /usr/bin/git clone git@github:artsy/Specs.git -- artsy-specs
Cloning into 'artsy-specs'...
ssh: Could not resolve hostname github: nodename nor servname provided, or not known
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```
> Fix URL to the Artsy CocoaPods specs repository

- source/using/the-podfile.html.md
Updated some incorrect information about the optimistic operator when only including the major version (e.g. `~> 1`). Will make a follow up PR to the [syntax page](https://guides.cocoapods.org/syntax/podfile.html#pod) to include an example like this, too.
I've verified this in a quick sample project using SSKeychain on CocoaPods 1.9.1.
```
pod 'SSKeychain', '~> 0'
```
installs SSKeychain 0.2.1, not 1.4.1 as the documentation would suggest.
> The Podfile: Update information about ~> operator

- source/making/private-cocoapods.html.md
Add a tad more context to the private CocoaPods documentation. I struggled with some issues as I understood I had to add my private repository (the pod to add) to the installation, rather than the Spec repository.
> Improve naming

- source/contributing/dev-environment.html.md
Remove Rainforest references that do more harm than good for new developers.
See also https://github.com/CocoaPods/Rainforest/pull/90
> Remove Rainforest from dev instructions

- source/using/using-cocoapods.html.md
I found the [`third link`](https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/installer/target_installer.rb#L40-L61) in `What is happening behind the scenes?` on [`this page`](https://guides.cocoapods.org/using/using-cocoapods.html) was not working properly. 
Perhaps it was caused by the change in the directory, so I found the link that I thought was appropriate and applied it.
Please check it out!
> restore `What is happening behind the scenes?` link

- source/using/a-gemfile.html.md
- source/using/faq.html.md
- source/using/pod-install-vs-update.html.md
- source/using/test-specs.html.md
- source/using/the-podfile.html.md
- source/using/troubleshooting.html.md
- source/using/unreleased-features.html.md
As we can see in `using/unreleased-features.html.md`, the order of this article is `0`, which is must wrong:
```
---
title: Using Unreleased Features
description: Instructions to use CocoaPods from a feature branch or a Work-in-progress fork
ignore: true
order: 0
thanks: "Sachin Palewar"
---
```
This wrong order number lead to the position of this article is too front:
Current order number of articles in `using` folder is here, there are two _repetitive_ items:
| article  |  order |
|---|---|
| getting-started.html   | 0  |
|  unreleased-features.html |  0 |
|  using-cocoapods.html |  1 |
| pod-install-vs-update.html  | 1 |
| the-podfile.html  | 2 |
| troubleshooting.html  | 3 |
| faq.html 	 | 4 |
| test-specs.html  | 5 |
| a-gemfile.html  | 6 |
I think `unreleased-features.html` should …
> Correct the order of the articles in the `using` folder.

- source/making/private-cocoapods.html.md
We will be removing this soon, and I noticed that the link is to master, so better to point to a current commit :)
> Update private-cocoapods.html.md to point to a specific commit
